variables:
  # Needed if you want automatic submodule checkout
  # For details see https://docs.gitlab.com/ee/ci/yaml/README.html#git-submodule-strategy
  GIT_SUBMODULE_STRATEGY: recursive
  SKA_CPP_DOCKER_BUILDER_IMAGE: artefact.skao.int/ska-cicd-cpp-build-base:0.2.10
  K8S_TEST_CLUSTER_TAG: k8srunner
  # OCI variables that overrides values in Makefile
  # CI Variables enable upstream/downstream CI integration
  PST_OCI_BUILDTOOLS_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-buildtools
  PST_OCI_BUILDTOOLS_IMAGE: ska-pst-buildtools
  PST_OCI_BUILDTOOLS_TAG: "0.0.0"
  PST_OCI_COMMON_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-common
  PST_OCI_COMMON_BUILDER: ska-pst-common-builder
  PST_OCI_COMMON_PROTO: ska-pst-common-proto
  PST_OCI_COMMON_TAG: ""
  OCI_IMAGE_BUILD_CONTEXT: $(PWD)
  OCI_IMAGE: "$PST_OCI_COMMON_BUILDER $PST_OCI_COMMON_PROTO"

image: $SKA_CPP_DOCKER_BUILDER_IMAGE

stages:
  - build
  - lint
  - test
  - publish
  - scan
  - pages

docs-build:
  stage: build
  image: registry.gitlab.com/ska-telescope/pst/ska-pst-common/ska-pst-common-builder:0.3.0
  needs:
  - oci-image-build

docs-pages:
  stage: pages
  image: registry.gitlab.com/ska-telescope/pst/ska-pst-common/ska-pst-common-builder:0.3.0
  needs:
  - oci-image-build

include:
  # OCI
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/oci-image.gitlab-ci.yml'

  # Conan
  # - project: 'ska-telescope/templates-repository'
  #   file: 'gitlab-ci/includes/conan.gitlab-ci.yml'

  # Helm
  # - project: 'ska-telescope/templates-repository'
  #   file: 'gitlab-ci/includes/helm-chart.gitlab-ci.yml'

  # K8s
  # - project: 'ska-telescope/templates-repository'
  #   file: 'gitlab-ci/includes/k8s.gitlab-ci.yml'

  # Docs pages
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'

  # Common runtime tests
  - local: '.gitlab/ci/tests.gitlab-ci.yml'

  # Create Gitlab CI badges from CI metrics
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

  # Umbrella include for all Raw life cycle stages
  - project: 'ska-telescope/templates-repository'
    file: gitlab-ci/includes/release.gitlab-ci.yml

  # Downstream pipeline trigger
  - local: '.gitlab/ci/downstream.gitlab-ci.yml'
    rules:
      - if: ($CI_COMMIT_BRANCH =~ /at3.*|main/) && ($CI_PIPELINE_SOURCE != "pipeline")
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"

oci-image-build:
  variables:
    OCI_BUILD_ADDITIONAL_ARGS: " --build-arg BUILD_IMAGE=$PST_OCI_BUILDTOOLS_REGISTRY/$PST_OCI_BUILDTOOLS_IMAGE:$PST_OCI_BUILDTOOLS_TAG"