# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  apt_packages:
    - protobuf-compiler
    - tar
    - gzip
    - curl
  jobs:
    post_system_dependencies:
      - curl -L -O https://go.dev/dl/go1.19.1.linux-amd64.tar.gz
      - tar -xzf go1.19.1.linux-amd64.tar.gz
      - ./go/bin/go install -v github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@v1.5.1
    pre_build:
      - protoc -I=./protobuf --plugin=protoc-gen-doc=./go/bin/protoc-gen-doc --doc_out=./docs/src/api --doc_opt=./protobuf/protobuf.md.mustache,protobuf.md ./protobuf/ska/pst/lmc/ska_pst_lmc.proto

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/src/conf.py

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/requirements.txt
 