oci-image-build:
  variables:
    OCI_BUILD_ADDITIONAL_ARGS: " --build-arg BUILD_IMAGE=$PST_OCI_BUILDTOOLS_REGISTRY/$PST_OCI_BUILDTOOLS_IMAGE:$PST_OCI_BUILDTOOLS_TAG"

.downstream_branch:
  trigger:
    branch: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME

.downstream_common_config:
  extends: .downstream_branch
  stage: test
  needs: ["dynamic_vars"]
  inherit:
    variables: false
  variables:
    OCI_SKIP_PUSH: "true"
  trigger:
    strategy: depend

trigger-merge-ska-pst-smrb:
  extends: .downstream_common_config
  variables:
    PST_OCI_COMMON_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-common
    PST_OCI_COMMON_TAG: $PST_OCI_COMMON_TAG
  needs:
    - trigger-merge-ska-pst-common
  trigger:
    project: ska-telescope/pst/ska-pst-smrb

trigger-merge-ska-pst-recv:
  extends: .downstream_common_config
  variables:
    PST_SMRB_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-smrb
  needs:
    - trigger-merge-ska-pst-smrb
  trigger:
    project: ska-telescope/pst/ska-pst-recv

trigger-merge-ska-pst-dsp:
  extends: .downstream_common_config
  variables:
    PST_SMRB_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-smrb
  needs:
    - trigger-merge-ska-pst-smrb
  trigger:
    project: ska-telescope/pst/ska-pst-dsp

trigger-merge-ska-pst-integration:
  extends: .downstream_common_config
  variables:
    PST_SMRB_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-smrb
    PST_RECV_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-recv
    PST_DSP_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-dsp
  needs:
    - trigger-merge-ska-pst-recv
    - trigger-merge-ska-pst-dsp
  trigger:
    project: ska-telescope/pst/ska-pst-integration