.downstream_release_branch:
  stage: test
  trigger:
    branch: $CI_DEFAULT_BRANCH

.downstream_release_common_config:
  extends: .downstream_release_branch
  inherit:
    variables: false
  variables:
    OCI_SKIP_PUSH: "true"
  trigger:
    strategy: depend

trigger-release-ska-pst-smrb:
  extends: .downstream_release_common_config
  variables:
    PST_OCI_COMMON_REGISTRY: $PST_OCI_COMMON_REGISTRY
    PST_OCI_COMMON_TAG: $PST_OCI_COMMON_TAG
  trigger:
    project: ska-telescope/pst/ska-pst-smrb
  when: manual

trigger-release-ska-pst-recv:
  extends: .downstream_release_common_config
  variables:
    PST_SMRB_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-smrb
  needs:
    - trigger-release-ska-pst-smrb
  trigger:
    project: ska-telescope/pst/ska-pst-recv
  when: manual

trigger-release-ska-pst-dsp:
  extends: .downstream_release_common_config
  variables:
    PST_SMRB_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-smrb
  needs:
    - trigger-release-ska-pst-smrb
  trigger:
    project: ska-telescope/pst/ska-pst-dsp
  when: manual

trigger-release-ska-pst-integration:
  extends: .downstream_release_common_config
  variables:
    PST_SMRB_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-smrb
    PST_RECV_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-recv
    PST_DSP_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-dsp
  needs:
    - trigger-release-ska-pst-recv
    - trigger-release-ska-pst-dsp
  trigger:
    project: ska-telescope/pst/ska-pst-integration
  when: manual