dynamic_vars:
  stage: build
  needs: ["oci-image-build"]
  script:
    - echo "PST_OCI_COMMON_TAG=$(grep -m 1 -o '[0-9].*' .release)-dev.c${CI_COMMIT_SHORT_SHA}" > build.env
  artifacts:
    reports:
      dotenv: build.env

trigger-ska-pst-smrb:
  stage: test
  needs:
    - dynamic_vars
    - oci-image-build
  inherit:
    variables: false
  variables:
    OCI_SKIP_PUSH: "true"
    PST_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-common
    PST_OCI_COMMON_TAG: $PST_OCI_COMMON_TAG
  trigger:
    project: ska-telescope/pst/ska-pst-smrb
    branch: $CI_COMMIT_BRANCH


trigger-ska-pst-recv:
  stage: test
  needs:
    - dynamic_vars
    - trigger-ska-pst-smrb
  inherit:
    variables: false
  variables:
    OCI_SKIP_PUSH: "true"
    PST_SMRB_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-smrb
    PST_SMRB_OCI_COMMON_TAG: $PST_SMRB_OCI_COMMON_TAG
  trigger:
    project: ska-telescope/pst/ska-pst-recv
    branch: $CI_COMMIT_BRANCH
    strategy: depend


trigger-ska-pst-dsp:
  stage: test
  needs:
    - dynamic_vars
    - trigger-ska-pst-smrb
  inherit:
    variables: false
  variables:
    OCI_SKIP_PUSH: "true"
    PST_SMRB_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-smrb
    PST_SMRB_OCI_COMMON_TAG: $PST_SMRB_OCI_COMMON_TAG
  trigger:
    project: ska-telescope/pst/ska-pst-dsp
    branch: $CI_COMMIT_BRANCH
    strategy: depend

trigger-ska-pst-integration:
  stage: test
  needs:
    - dynamic_vars
    - trigger-ska-pst-recv
    - trigger-ska-pst-dsp
  inherit:
    variables: false
  variables:
    OCI_SKIP_PUSH: "true"
    PST_RECV_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-recv
    PST_RECV_OCI_TAG: $PST_SMRB_OCI_COMMON_TAG
  trigger:
    project: ska-telescope/pst/ska-pst-integration
    branch: $CI_COMMIT_BRANCH
    strategy: depend