.downstream_branch:
  trigger:
    branch: $CI_COMMIT_BRANCH
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH

.downstream_branch:
  trigger:
    branch: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    strategy: depend
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME

.downstream_common_config:
  extends: .downstream_branch
  stage: test
  needs: ["dynamic_vars"]
  inherit:
    variables: false
  variables:
    OCI_SKIP_PUSH: "true"
    PST_OCI_COMMON_REGISTRY: "registry.gitlab.com/ska-telescope/pst/ska-pst-common"
    PST_OCI_COMMON_TAG: $PST_OCI_COMMON_TAG

trigger-ska-pst-smrb:
  extends: .downstream_common_config
  trigger:
    project: ska-telescope/pst/ska-pst-smrb


trigger-ska-pst-recv:
  extends: .downstream_common_config
  needs:
    - trigger-ska-pst-smrb
  trigger:
    project: ska-telescope/pst/ska-pst-recv


trigger-ska-pst-dsp:
  extends: .downstream_common_config
  needs:
    - trigger-ska-pst-smrb
  trigger:
    project: ska-telescope/pst/ska-pst-dsp

trigger-ska-pst-integration:
  extends: .downstream_common_config
  needs:
    - trigger-ska-pst-smrb
    - trigger-ska-pst-recv
    - trigger-ska-pst-dsp
  trigger:
    project: ska-telescope/pst/ska-pst-integration