trigger-ska-pst-smrb:
  stage: build
  inherit:
    variables: false
  variables:
    PST_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-common
  trigger:
    project: ska-telescope/pst/ska-pst-smrb
    branch: at3-322-downstream-ci-trigger