# Test OCI
dynamic_vars:
  tags:
    - $K8S_TEST_CLUSTER_TAG
  stage: test
  script:
    - echo "OCI_TEST_TAG=$(grep -m 1 -o '[0-9].*' .release)-dev.c${CI_COMMIT_SHORT_SHA}" > build.env
  artifacts:
    reports:
      dotenv: build.env

test_dada:
  tags:
    - $K8S_TEST_CLUSTER_TAG
  variables:
    OCI_TEST_IMAGE: "registry.gitlab.com/ska-telescope/pst/ska-pst-common/ska-pst-common-builder"
    GIT_SUBMODULE_STRATEGY: normal
  stage: test
  needs:
    - oci-image-build
    - dynamic_vars
  image: "$OCI_TEST_IMAGE:$OCI_TEST_TAG"
  script:
    - dada_db
    - dada_db -d