# Test OCI
test_dada:
  tags:
    - $K8S_TEST_CLUSTER_TAG
  variables:
    PST_OCI_COMMON_REGISTRY: "registry.gitlab.com/ska-telescope/pst/ska-pst-common/ska-pst-common-builder"
    GIT_SUBMODULE_STRATEGY: normal
  stage: test
  needs:
    - oci-image-build
    - dynamic_vars
  image: "$PST_OCI_COMMON_REGISTRY:$PST_OCI_COMMON_TAG"
  script:
    - dada_db
    - dada_db -d