# Test OCI
test_proto:
  variables:
    OCI_TEST_IMAGE: "registry.gitlab.com/ska-telescope/pst/ska-pst-common/ska-pst-common-builder"
  stage: test
  needs:
    - "oci-image-build"
  image: "$OCI_TEST_IMAGE:$OCI_TEST_TAG"
  script:
    - protoc --version
    - make local-proto-test