dynamic_vars:
  stage: build
  needs: ["oci-image-build"]
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - echo "PST_OCI_COMMON_TAG=$(grep -m 1 -o '[0-9].*' .release)-dev.c${CI_COMMIT_SHORT_SHA}" > build.env
  artifacts:
    reports:
      dotenv: build.env

# Test OCI
test_dada:
  tags:
    - $K8S_TEST_CLUSTER_TAG
  variables:
    PST_OCI_COMMON_REGISTRY: "registry.gitlab.com/ska-telescope/pst/ska-pst-common/ska-pst-common-builder"
    GIT_SUBMODULE_STRATEGY: normal
  stage: test
  needs:
    - dynamic_vars
  image: "$PST_OCI_COMMON_REGISTRY:$PST_OCI_COMMON_TAG"
  script:
    - dada_db
    - dada_db -d